server:
  port: 8082

spring:
  application:
    name: profile-service

  datasource:
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/copavor
    driver-class-name: org.postgresql.Driver

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
